<?php
// index.php (Dashboard)
require 'db.php';
require 'functions.php';
require 'auth.php';

// Stats Queries
$total_products = $pdo->query("SELECT COUNT(*) FROM products")->fetchColumn();
$in_stock = $pdo->query("SELECT COUNT(*) FROM products WHERE quantity > min_stock_level")->fetchColumn();
$low_stock = $pdo->query("SELECT COUNT(*) FROM products WHERE quantity <= min_stock_level AND quantity > 0")->fetchColumn();
$out_of_stock = $pdo->query("SELECT COUNT(*) FROM products WHERE quantity = 0")->fetchColumn();

// Period Selection for Chart
$period = isset($_GET['period']) ? (int)$_GET['period'] : 6;
if (!in_array($period, [3, 6, 12])) $period = 6;

// Stock Movement Summary
$months = [];
$stock_in_data = [];
$stock_out_data = [];

for ($i = $period - 1; $i >= 0; $i--) {
    $month_start = date('Y-m-01', strtotime("-$i months"));
    $month_end = date('Y-m-t', strtotime("-$i months"));
    $month_label = date('M', strtotime("-$i months"));
    
    $in = $pdo->query("SELECT SUM(quantity) FROM stock_movements WHERE type='in' AND created_at BETWEEN '$month_start 00:00:00' AND '$month_end 23:59:59'")->fetchColumn() ?: 0;
    $out = $pdo->query("SELECT SUM(quantity) FROM stock_movements WHERE type='out' AND created_at BETWEEN '$month_start 00:00:00' AND '$month_end 23:59:59'")->fetchColumn() ?: 0;
    
    $months[] = $month_label;
    $stock_in_data[] = $in;
    $stock_out_data[] = $out;
}

// Today statistics (for quick reference cards)
$today = date('Y-m-d');
$stock_in_today = $pdo->query("SELECT SUM(quantity) FROM stock_movements WHERE type='in' AND DATE(created_at) = '$today'")->fetchColumn() ?: 0;
$stock_out_today = $pdo->query("SELECT SUM(quantity) FROM stock_movements WHERE type='out' AND DATE(created_at) = '$today'")->fetchColumn() ?: 0;

// Chart Data: Stock by Category
$categories_stmt = $pdo->query("SELECT c.name, COUNT(p.id) as count FROM categories c LEFT JOIN products p ON c.id = p.category_id GROUP BY c.id");
$cat_labels = [];
$cat_data = [];
while($row = $categories_stmt->fetch()) {
    $cat_labels[] = $row['name'];
    $cat_data[] = $row['count'];
}

include 'includes/header.php';
?>

    <!-- Banner Slider -->
    <div class="banner-wrapper animate-fade-in">
        <div class="banner-slider" id="bannerSlider">
            <div class="banner-slide"><img src="img/banner1.webp" alt="Banner 1"></div>
            <div class="banner-slide"><img src="img/banner2.webp" alt="Banner 2"></div>
            <div class="banner-slide"><img src="img/banner3.webp" alt="Banner 3"></div>
            <div class="banner-slide"><img src="img/banner4.webp" alt="Banner 4"></div>
            <div class="banner-slide"><img src="img/banner5.webp" alt="Banner 5"></div>
            <div class="banner-slide"><img src="img/banner6.webp" alt="Banner 6"></div>
            <div class="banner-slide"><img src="img/banner7.jpg" alt="Banner 7"></div>
        </div>
        <div class="banner-dots" id="bannerDots">
            <!-- Dots generated by JS -->
        </div>
    </div>
    
    <script>
        document.addEventListener('DOMContentLoaded', function() {
            const slider = document.getElementById('bannerSlider');
            if (slider) {
                const slides = slider.querySelectorAll('.banner-slide');
                const dotsContainer = document.getElementById('bannerDots');
                const slideCount = slides.length;
                let currentIndex = 0;
                
                // Create Dots
                for (let i = 0; i < slideCount; i++) {
                    const dot = document.createElement('div');
                    dot.className = i === 0 ? 'banner-dot active' : 'banner-dot';
                    dot.addEventListener('click', () => goToSlide(i));
                    dotsContainer.appendChild(dot);
                }
                
                const dots = dotsContainer.querySelectorAll('.banner-dot');

                function goToSlide(index) {
                    currentIndex = index;
                    slider.style.transform = `translateX(-${currentIndex * 100}%)`;
                    
                    // Update dots
                    dots.forEach(d => d.classList.remove('active'));
                    dots[currentIndex].classList.add('active');
                }
                
                function nextSlide() {
                    currentIndex = (currentIndex + 1) % slideCount;
                    goToSlide(currentIndex);
                }
                
                // Auto Slide every 4 seconds
                let slideInterval = setInterval(nextSlide, 4000);
                
                // Pause on hover
                const wrapper = document.querySelector('.banner-wrapper');
                if(wrapper) {
                    wrapper.addEventListener('mouseenter', () => clearInterval(slideInterval));
                    wrapper.addEventListener('mouseleave', () => slideInterval = setInterval(nextSlide, 4000));
                }
            }
        });
    </script>

<div class="dashboard-controls animate-fade-in" style="margin-bottom: 2rem; display: flex; justify-content: space-between; align-items: center; gap: 15px; background: rgba(255,255,255,0.4); padding: 15px; border-radius: 12px; backdrop-filter: blur(10px); border: 1px solid rgba(255,255,255,0.2);">
    <div class="filter-group" style="display: flex; align-items: center; gap: 10px;">
        <span style="font-weight: 600; color: #555;">View Analysis:</span>
        <select onchange="window.location.href='?period='+this.value" class="glass-select" style="padding: 8px 15px; border-radius: 8px; border: 1px solid rgba(176, 137, 104, 0.3); background: white; outline: none; cursor: pointer;">
            <option value="3" <?php echo $period == 3 ? 'selected' : ''; ?>>Last 3 Months</option>
            <option value="6" <?php echo $period == 6 ? 'selected' : ''; ?>>Last 6 Months</option>
            <option value="12" <?php echo $period == 12 ? 'selected' : ''; ?>>Last 12 Months</option>
        </select>
    </div>
    <div class="export-group" style="display: flex; gap: 10px;">
        <button onclick="exportDashboardExcel()" class="btn btn-primary" style="background: #2D6A4F; border: none; padding: 10px 18px; border-radius: 8px; color: white; display: flex; align-items: center; gap: 8px; cursor: pointer;">
            <i class="fas fa-file-excel"></i> Export Excel
        </button>
        <button onclick="exportDashboardPDF()" class="btn btn-primary" style="background: #D00000; border: none; padding: 10px 18px; border-radius: 8px; color: white; display: flex; align-items: center; gap: 8px; cursor: pointer;">
            <i class="fas fa-file-pdf"></i> Export PDF
        </button>
    </div>
</div>



<!-- Stats Grid -->
<div id="statsSection" class="dashboard-grid animate-fade-in" style="animation-delay: 0.1s;">
    <div class="glass-card stat-card">
        <div class="stat-header">
            <span>Total Items</span>
            <i class="fa-solid fa-box-open" style="color: var(--primary-color);"></i>
        </div>
        <div class="stat-value"><?php echo $total_products; ?></div>
        <div class="stat-trend trend-up">
            <i class="fa-solid fa-arrow-trend-up"></i> In Inventory
        </div>
    </div>
    <div class="glass-card stat-card">
        <div class="stat-header">
            <span>In Stock</span>
            <i class="fa-solid fa-check-circle" style="color: #2D6A4F;"></i>
        </div>
        <div class="stat-value" style="color: #2D6A4F;"><?php echo $in_stock; ?></div>
        <div class="stat-trend trend-up">
             available for sale
        </div>
    </div>
    <div class="glass-card stat-card">
        <div class="stat-header">
            <span>Low Stock</span>
            <i class="fa-solid fa-triangle-exclamation" style="color: #E76F51;"></i>
        </div>
        <div class="stat-value" style="color: #E76F51;"><?php echo $low_stock; ?></div>
        <div class="stat-trend trend-down">
            <i class="fa-solid fa-arrow-trend-down"></i> Needs attention
        </div>
    </div>
    <div class="glass-card stat-card">
        <div class="stat-header">
            <span>Out of Stock</span>
            <i class="fa-solid fa-times-circle" style="color: #D00000;"></i>
        </div>
        <div class="stat-value" style="color: #D00000;"><?php echo $out_of_stock; ?></div>
        <div class="stat-trend">
            <span style="font-size: 0.8rem; color: var(--text-light);">Restock required</span>
        </div>
    </div>
</div>

<!-- Charts Row -->
<div id="chartsSection" class="charts-container animate-fade-in" style="animation-delay: 0.2s;">
    <div class="glass-card chart-card" id="movementCard">
        <h3 style="margin-bottom: 1.5rem;">Stock Movements (Last <?php echo $period; ?> Months)</h3>
        <div style="display: flex; justify-content: space-around; margin-bottom: 20px;">
             <div class="text-center">
                <h4 class="text-success" style="color: #2D6A4F;"><i class="fas fa-arrow-down"></i> <?php echo number_format(array_sum($stock_in_data)); ?></h4>
                <p>Total In</p>
            </div>
            <div class="text-center">
                <h4 class="text-danger" style="color: #D00000;"><i class="fas fa-arrow-up"></i> <?php echo number_format(array_sum($stock_out_data)); ?></h4>
                <p>Total Out</p>
            </div>
        </div>
        <canvas id="stockMovementChart"></canvas>
    </div>
    <div class="glass-card chart-card" id="categoryCard">
        <h3 style="margin-bottom: 1.5rem;">Stock by Category</h3>
        <canvas id="categoryChart"></canvas>
    </div>
</div>

<?php include 'includes/footer.php'; ?>

<script>
// Category Chart
const ctxCat = document.getElementById('categoryChart').getContext('2d');
new Chart(ctxCat, {
    type: 'doughnut',
    data: {
        labels: <?php echo json_encode($cat_labels); ?>,
        datasets: [{
            data: <?php echo json_encode($cat_data); ?>,
            backgroundColor: ['#B08968', '#D4A373', '#E6CCB2', '#E5989B', '#6D6875', '#FDF4EB'],
            borderWidth: 0,
            hoverOffset: 10
        }]
    },
    options: {
        responsive: true,
        animation: {
            onComplete: function() {
                window.categoryChartReady = true;
            }
        },
        plugins: {
            legend: { 
                position: 'bottom',
                labels: {
                    font: {
                        family: 'Outfit'
                    },
                    padding: 20,
                    usePointStyle: true
                } 
            }
        },
        layout: {
            padding: 20
        }
    }
});

// Monthly Movement Trend Chart
const ctxMov = document.getElementById('stockMovementChart').getContext('2d');
new Chart(ctxMov, {
    type: 'line',
    data: {
        labels: <?php echo json_encode($months); ?>,
        datasets: [
            {
                label: 'Stock In',
                data: <?php echo json_encode($stock_in_data); ?>,
                borderColor: '#2D6A4F',
                backgroundColor: 'rgba(45, 106, 79, 0.1)',
                borderWidth: 3,
                tension: 0.4,
                fill: true,
                pointBackgroundColor: '#2D6A4F'
            },
            {
                label: 'Stock Out',
                data: <?php echo json_encode($stock_out_data); ?>,
                borderColor: '#D00000',
                backgroundColor: 'rgba(208, 0, 0, 0.1)',
                borderWidth: 3,
                tension: 0.4,
                fill: true,
                pointBackgroundColor: '#D00000'
            }
        ]
    },
    options: {
        responsive: true,
        animation: {
            onComplete: function() {
                window.movementChartReady = true;
            }
        },
        plugins: {
            legend: {
                position: 'bottom',
                labels: {
                    font: { family: 'Outfit' },
                    usePointStyle: true,
                    padding: 20
                }
            }
        },
        scales: {
            y: {
                beginAtZero: true,
                grid: { color: 'rgba(0,0,0,0.05)' }
            },
            x: {
                grid: { display: false }
            }
        }
    }
});

// Export Functions
async function exportDashboardPDF() {
    const { jsPDF } = window.jspdf;
    const doc = new jsPDF('p', 'mm', 'a4');
    
    // Add title
    doc.setFontSize(22);
    doc.setTextColor(176, 137, 104); // Rose Gold color
    doc.text("Inventory Dashboard Analysis", 105, 15, { align: "center" });
    doc.setFontSize(10);
    doc.setTextColor(100);
    doc.text(`Generated on: ${new Date().toLocaleString()} | Analysis Period: Last <?php echo $period; ?> Months`, 105, 22, { align: "center" });

    // Capture stats cards
    const statsCanvas = await html2canvas(document.getElementById('statsSection'), { scale: 2 });
    const statsImg = statsCanvas.toDataURL('image/png');
    doc.addImage(statsImg, 'PNG', 10, 30, 190, 40);

    // Capture charts (one by one for better resolution)
    const movCanvas = await html2canvas(document.getElementById('movementCard'), { scale: 2 });
    const movImg = movCanvas.toDataURL('image/png');
    doc.addImage(movImg, 'PNG', 10, 80, 190, 100);

    const catCanvas = await html2canvas(document.getElementById('categoryCard'), { scale: 2 });
    const catImg = catCanvas.toDataURL('image/png');
    doc.addImage(catImg, 'PNG', 50, 190, 110, 80);

    doc.save(`tkbytyra_dashboard_report_${new Date().toISOString().slice(0,10)}.pdf`);
}

function exportDashboardExcel() {
    const period = "<?php echo $period; ?>";
    const months = <?php echo json_encode($months); ?>;
    const stockIn = <?php echo json_encode($stock_in_data); ?>;
    const stockOut = <?php echo json_encode($stock_out_data); ?>;
    
    const data = [
        ["TKBYTYRA INVENTORY ANALYSIS REPORT"],
        ["Analysis Period", `Last ${period} Months`],
        ["Generated On", new Date().toLocaleString()],
        [],
        ["SUMMARY STATISTICS"],
        ["Metric", "Value"],
        ["Total Products", "<?php echo $total_products; ?>"],
        ["Items In Stock", "<?php echo $in_stock; ?>"],
        ["Items Low Stock", "<?php echo $low_stock; ?>"],
        ["Items Out of Stock", "<?php echo $out_of_stock; ?>"],
        [],
        ["MONTHLY PERFORMANCE"],
        ["Month", "Stock In", "Stock Out"]
    ];

    months.forEach((m, i) => {
        data.push([m, stockIn[i], stockOut[i]]);
    });

    const ws = XLSX.utils.aoa_to_sheet(data);
    const wb = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(wb, ws, "Dashboard Analysis");
    
    // Formatting can be added here if needed
    XLSX.writeFile(wb, `tkbytyra_dashboard_data_${new Date().toISOString().slice(0,10)}.xlsx`);
}
</script>
